apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: immutable-no-bash
  name: immutable-no-bash
spec:
  containers:
  - image: httpd
    name: immutable-no-bash
    resources: {}
    startupProbe:
      exec:
        command:
        - rm
        - /bin/bash
      initialDelaySeconds: 2
      periodSeconds: 5
status: {}
